import React from "react";

function TableHeader() {
  return (
    <>
      <tr>
        <th data-filter-control="select" data-sortable="true" data-field="id">
          id
        </th>
        <th
          data-field="Campaign"
          data-filter-control="input"
          data-sortable="true"
        >
          Campaign
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-field="State"
        >
          State
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-field="status"
        >
          Status
        </th>
        <th data-filter-control="select" data-sortable="true" data-field="type">
          type
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-field="targeting"
        >
          targeting
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="campaign_bidding_strategy"
        >
          campaign_bidding_strategy
        </th>
        <th
          data-filter-control="input"
          data-sortable="true"
          data-visible="false"
          data-field="start_date"
        >
          start_date
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="end_Date"
        >
          end_Date
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="portfolio"
        >
          portfolio
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="Budget"
        >
          budget
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="top_of_search_is"
        >
          top_of_search_is
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="cost_type"
        >
          cost_type
        </th>
        <th
          data-filter-control="input"
          data-sortable="true"
          data-visible="false"
          data-field="impressions"
        >
          impressions
        </th>
        <th
          data-filter-control="select"
          data-sortable="true "
          data-visible="false"
          data-field="clicks"
        >
          clicks
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="ctr"
        >
          ctr
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="Spend"
        >
          Spend
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="Cpc"
        >
          Cpc
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="orders"
        >
          orders
        </th>
        <th
          data-filter-control="input"
          data-sortable="true"
          data-visible="false"
          data-field="sales"
        >
          sales
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="acos"
        >
          acos
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="roas"
        >
          roas
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="ntb_order"
        >
          ntb_order
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="percent_of_orders_ntb"
        >
          percent_of_orders_ntb
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="ntb_sales"
        >
          ntb_sales
        </th>
        <th
          data-filter-control="input"
          data-sortable="true"
          data-visible="false"
          data-field="percent_of_sales_nto"
        >
          percent_of_sales_nto
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="viewable_impressions"
        >
          viewable_impressions
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="vcom"
        >
          vcom
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="created_dttm"
        >
          created_dttm
        </th>
        <th
          data-filter-control="select"
          data-sortable="true"
          data-visible="false"
          data-field="modified_dttm"
        >
          modified_dttm
        </th>
      </tr>
    </>
  );
}

export default TableHeader;
